Adding support for episode/series title, episode/season number, and more
rmrector/script.playrandomvideos pull request #7
Opened 2021-09-07 17:00 UTC by wietze

This PR will ensure the following attributes are included in new `ListItems` for episodes:
- Season Number
- Episode Number
- Series Title
- Episode Title
- Play count
- Rating
- User Rating

This ensures when looking at the playlist in a TV remote app such as Kore, the data will be more complete.
Similarly, other addons relying on episode information (such as Up Next) will benefit from this too.

2022-02-04 02:38 UTC, rmrector requested changes
Sorry for letting this set. I've commented one small change.

2022-02-04 02:38 UTC, rmrector commented on python/lib/listitembuilder.py
> +    if 'title' in item:
Set 'title' in the `infokey_map` along with the other new keys, rather than overwriting label here.

2022-02-04 17:32 UTC, wietze commented
Sure thing, updated.

2022-02-05 01:03 UTC, merged

2022-02-05 01:03 UTC, rmrector commented
Thanks! Merged and I'll get this into the next version.