Feature: Control addition of recently watched videos
rmrector/script.playrandomvideos pull request #8
Opened 2022-01-29 17:30 UTC by porternw

A purely "random" playlist will sometimes queue episodes that have been recently watched. This pull request adds the ability to filter out episodes/movies that have been played recently using Kodi's lastplayed filter. You can specify in the settings how many months back you want to avoid adding to the queue. I made it work for movies and tvshows, though it could be easily applied to any content. Thanks for the nice script!

2022-02-04 02:32 UTC, rmrector requested changes
Cheers. I've commented a few small changes.

2022-02-04 02:32 UTC, rmrector commented on python/lib/playrandom.py
> +# Don't play video that has been watched in the past x months
This commented code looks like leftovers that can be removed.

2022-02-04 02:32 UTC, rmrector commented on python/lib/playrandom.py
> +    # Don't play video that has been watched in the past x months
Pack all of this into a top-level function like `_build_watched_before_filter` that returns the filter. Then call it only in the `elif` block below when in this mode.

2022-02-04 02:32 UTC, rmrector commented on python/lib/playrandom.py
> +    today = datetime.today()
`datetime` can be finicky in Kodi. Luckily there is an operator `notinthelast` that takes in a number of days, so you should be able to rework this to not need datetime or timedelta at all.

2022-02-05 20:33 UTC, porternw commented on python/lib/playrandom.py
> +# Don't play video that has been watched in the past x months
Commented code cleaned up.

2022-02-05 20:34 UTC, porternw commented on python/lib/playrandom.py
> +    # Don't play video that has been watched in the past x months
Built top-level function "_build_watched_before_filter".

2022-02-05 20:35 UTC, porternw commented on python/lib/playrandom.py
> +    today = datetime.today()
Used kodi builtin operator "notinthelast" instead of datetime and timedelta.

2022-02-06 21:20 UTC, rmrector approved these changes

2022-02-06 21:21 UTC, merged

2022-02-06 21:21 UTC, rmrector commented
Cheers, thanks

2022-02-06 21:42 UTC, porternw commented
Thank you!